export default {
  async fetch(req) {  // Define an async function that takes a request object as input
    
    const data =
      req.cf !== undefined  // If the request contains a Cloudflare Object
        ? req.cf  // Use that Cloudflare Object
        : { error: "The `cf` object is not available inside the preview." };  // Otherwise, return an error message
    
    // Convert the request headers into an object and format them nicely as a JSON string
    const headersObject = Object.fromEntries(req.headers)
    const requestHeaders = JSON.stringify(headersObject, null, 2)

    // Define the HTML markup to be returned by the response
    const html = `<!DOCTYPE html >
      <head><title>simple worker</title></head>
      <body>
        <h1>Hello World</h1>
        <p>This markup was generated by a Cloudflare Worker.</p>
        <pre>Cloudflare Object: ${JSON.stringify(data, null, 2)}</pre>
        <pre>Request headers: ${requestHeaders}</pre>
      </body>
    </html>`;

    // Return a new Response object containing the HTML markup
    return new Response(html, {
      headers: {
        "content-type": "text/html",
      },
    });
  }
}
